services:
  - type: web
    name: task-manager-backend
    env: node
    branch: main
    root: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://hxsingh25_db_user:ue3fZmYTmirNB1dg@cluster0.valaz5w.mongodb.net/taskmanager?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: abc123xyz789abc123xyz789abc123xyz789
      - key: FRONTEND_URL
        value: https://task-manager-frontend-og8qhon9z-harshits-projects3.vercel.app
